### ISSUE TITLE
Error exception in Chrome

### ISSUE THREAD

**Issue by richards1052** [njuljsong/wsjUnblock#10]
Using the latest version of Chrome, I have a WSJ article open in my tab.  Then I click on the "Make WJS Great Again" extension icon and this URL opens: http://blog.jinsongli.com/ & I get this error:

"ErrorException in Connector.php line 47:
SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111) (View: /var/www/blog/resources/views/posts/index.blade.php)"

Any way to fix this?

**Comment by njuljsong** [comment]
oh, it is my website down. It does not affect the extension to unblock websites. I'll fix it in the weekend!

**Comment by njuljsong** [comment]
my website is up now.
