### ISSUE TITLE
The Information

### ISSUE THREAD

**Issue by winstonma** [njuljsong/wsjUnblock#12]
Just wonder if [The Information](https://www.theinformation.com/) can be included?

Here is an [example](https://www.theinformation.com/cisco-replaces-collaboration-unit-chief-amid-weak-sales?shared=34b16e).

**Comment by njuljsong** [comment]
Hi @winstonma I do not have plan for that.

**Comment by winstonma** [comment]
@njuljsong Thanks for the reply.

By the way would it be possible that the filter rules are not embedded in the extension, but instead configurable in the settings.

**Comment by winstonma** [comment]
@hotcap Do you think there are some configs that could enable full text within The Information? Thanks

**Comment by hotcap** [comment]
@winstonma I wouldn't think so - I took a look and it appears to a similar situation as how medium.com affiliate platforms are set up, see my response on issue #9 for more details.

**Comment by winstonma** [comment]
@hotcap Thanks
