### ISSUE TITLE
The Ken

### ISSUE THREAD

**Issue by gnjnshh** [njuljsong/wsjUnblock#13]
Hello. Thanks for your work. I tried many ways to bypass the https://the-ken.com/ 's paywall, nothing worked. **Googlebot, archieve.is, outline.** If you can include in the bypassed sites or just give me general direction to bypass, since you are more equipped with the knowledge, I will be appreciative. 
Thanks.

**Comment by njuljsong** [comment]
Hi, @gnjnshh I don't have plan to add this one. If you read the readme and the source code, you can see I use 2 ways to unblock sites: filter javascript or filter request header. It is not a universal solution for any sites. so this approach might not work for this site.

**Comment by gnjnshh** [comment]
@njuljsong, thanks for the reply. Its got a very resilient paywall, I will keep trying to circumvent around it. Have a good day.
