### ISSUE TITLE
Extension fails with cooking.nytimes.com paywall overlay

### ISSUE THREAD

**Issue by strafer** [njuljsong/wsjUnblock#2]
The New York Times Cooking section <https://cooking.nytimes.com/> has gone behind a paywall that is separate from the main site paywall. As a result, your extension doesn't work with the Cooking section. Toggling javascript allows one to view the recipe but that, of course, breaks functionality with the rest of the site and prevents viewing one's recipe box. The Remove Overlay extension works, too, but it would be nice to have an extension that blocks the offending javascript automatically.

Do you have any suggestions for working around this section-specific paywall? Any chance your extension can be updated to handle the The New York Times Cooking section paywall?

**Comment by njuljsong** [comment]
@strafer that is an interesting problem to solve! It seems to me that they want people to register an account first, even for free trial. I don't have any better ideas than you mentioned.  I'll try removing overlay first.

**Comment by njuljsong** [comment]
@strafer I created a PR https://github.com/njuljsong/wsjUnblock/pull/3 for this. Would you mind taking a look?

**Comment by strafer** [comment]
Thanks for looking into this. 

I tested out your updated extension from the latest commit. So far, it seems to work well and doesn't require using a javascript toggler. Even clicking the greyed out recipes in the Recipe Box (which you need a free NY Times account to use) seems to work, unlike with the javascript togglers.

I haven't encountered any issues with playing videos if they accompany the recipe directly. However, the videos in the Cooking Guides (like the one you linked to) don't work. Same recipe with video on different pages, different results.

This video doesn't work: https://cooking.nytimes.com/guides/37-how-to-make-cassoulet
This video works: https://cooking.nytimes.com/recipes/1018520-cassoulet

Also, I still see a subscription reminder off to the left in the Recipe Box and most of the recipes are greyed out (but now clickable thanks to your changes). You can see what I mean in this screenshot:
![screenshot 2017-08-10 14 16 51](https://user-images.githubusercontent.com/4935512/29192787-9a64f978-7dd7-11e7-8d11-e9d676f307ef.png)

Thanks for your work. It's much appreciated.

**Comment by strafer** [comment]
Weirdly, the videos play fine in this cooking guide:
https://cooking.nytimes.com/guides/18-how-to-make-eggs

I wonder why the Cassoulet Guide doesn't work.
https://cooking.nytimes.com/guides/37-how-to-make-cassoulet

**Comment by njuljsong** [comment]
@strafer thanks a lot for your time for reviewing this. The video in the content head is playing without a problem, but the images and videos in the content body are all set to be lazyloaded, and they do not load. It has to do with javascript.

**Comment by strafer** [comment]
@njuljsong Okay, thanks for the explanation. 

I'm not a web developer or a programmer, so apologies if this is a stupid question: could the lazyloaded images in the Cooking Guides be loaded by your extension without triggering the subscription overlay? 

The reason I ask this is because I came across this article <https://appelsiini.net/projects/lazyload/>. This particular section stood out:

> Fallback for Non JavaScript Browsers
Practically everyone has JavaScript enabled. However if you still want to support non JavaScript users you can include the real image tag inside <noscript></noscript> block.

<img class="lazy" data-original="img/example.jpg"  width="640" heigh="480">
<noscript>
    <img src="img/example.jpg" width="640" heigh="480">
</noscript>
To prevent both placeholder and the real image showing at the same time hide the placeholder with css.

.lazy {
    display: none;
}
For JavaScript enabled browser you must enable displaying the placeholders when documents loads. This can be done at the same time when initializing the plugin.

$("img.lazy").show().lazyload();

**Comment by njuljsong** [comment]
@strafer  thanks for the tip! I found a fix just only using CSS! haha, you can verify that everything is working now!

**Comment by strafer** [comment]
You fixed it. Excellent work! Thanks.
