### ISSUE TITLE
Does it have to be reinstalled everytime ff/chrome updates?

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [njuljsong/wsjUnblock#30]
I noticed that after a while (a week or two) it doesn't work anymore and have no idea why.

Wonder if it's due to ff/chrome updates or something else?

Thank you for the program btw!

**Comment by alexvizitiu** [comment]
I dont think so.

I dont use the extension provided in this project and made my own .xpi with a couple of modified things, but i never had any issues with the plug-in not working because of Firefox updates, including Firefox mobile.
