### ISSUE TITLE
Suggestion - Sites

### ISSUE THREAD

**Issue by rourpab** [njuljsong/wsjUnblock#32]
Hello I'd like to suggest some sites not yet accessible through this extension.

- **National Law Journal** (https://www.law.com/nationallawjournal/2018/02/21/ruling-opening-door-to-rico-claims-against-gm-could-drive-other-emissions-cases/)
- **Boston Globe** (https://www.bostonglobe.com)
- **The Times** (https://www.thetimes.co.uk/edition/news/education-secretary-damian-hinds-plans-crackdown-on-illegal-schools-as-fears-of-radicalisation-grow-3rzgrkzcc)
- **Harvard Business Review** (https://hbr.org)
- **Breaking Views** (https://www.breakingviews.com)
- **Barron's** (https://www.barrons.com/articles/venezuelan-free-fall-would-give-oil-a-pop-1519437414)
- **Chicago Tribune** (http://www.chicagotribune.com/)
- **WSJ Pro** (https://www.wsj.com/articles/auto-supply-co-says-rival-bidder-beats-icahn-offer-at-bankruptcy-auction-1519852601)

**I realize this is a time consuming endeavor and I am willing to compen$ate any contributors for their efforts.**

**Comment by njuljsong** [comment]
hey @rourpab this repo is for fun, not for money.

**Comment by rourpab** [comment]
How can I donate anyway?
