### ISSUE TITLE
FYI 'The Australian' is now blocking the extension on Chrome

### ISSUE THREAD

**Issue by chesterrockwell** [njuljsong/wsjUnblock#5]

**Comment by njuljsong** [comment]
@chesterrockwell can you elaborate it? I do not get what you mean.

**Comment by chesterrockwell** [comment]
@njuljsong as of a few days ago bypass paywalls no longer circumvents the 'The Australian' paywall for premium content - eg most story links on this page (theaustralian.com.au/business) now redirect to the accounts page.  By the way bypass paywalls = very nice code!

**Comment by njuljsong** [comment]
I did some test for `theaustralian.com.au`, here is my observation: 
*  They enforce the web browser to not clear cookie.
*  Simply changing referrer to `www.twitter.com` does not work.
*  Even shorten urls embedded in twitter do not work, example: `https://twitter.com/dixydeans1/status/892207623986008064` has a link to `http://www.theaustralian.com.au/opinion/columnists/israel-losing-the-public-relations-war-against-palestinians/news-story/5f8ff49dc803393b069f2d3b5d6ead75&memtype=anonymous` but it will just redirect to the subscription page.

Not sure if they have any loopholes open...

**Comment by chesterrockwell** [comment]
ok thanks - sounds like a challenge...
